spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/job_search
    username: zhenya
    password: 132435465768798
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
